
package CUIInventario;

import Control.Control;
import GoOrderDTO.DatosReporteEntradaDTO;
import Pattern.BotonRedondeado;
import Pattern.ColorBoton;
import java.io.File;
import java.io.InputStream;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.example.NegocioException;

/**
 *
 * @author 
 */
public class HistorialProductosEntradaFORM extends javax.swing.JFrame {

    private final ColorBoton colorB;
    private final ColorBoton colorR;
    private final ColorBoton colorE;
    private final Control control;
    private DefaultTableModel entradaProductos;
    
    public HistorialProductosEntradaFORM(Control control) throws NegocioException {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
        this.control = control;                       
        
        colorB = new ColorBoton(btnBuscar);
        colorR = new ColorBoton(btnRegresar);
        colorE = new ColorBoton(btnExportar);
        
        String[] columnas = {"ID", "Nombre Producto", "Precio Producto", "Cantidad recibida", "Fecha y Hora"};
        this.entradaProductos = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }            
        };
        
        this.tbProductos.setModel(this.entradaProductos);
        this.tbProductos.setRowHeight(35);
    }
    
    private void llenarTabla() {
        Date inicio = jDateInicio.getDate();
        Date fin = jDateFinal.getDate();
        if (inicio == null || fin == null) {
            JOptionPane.showMessageDialog(this, 
                    "Las fechas no pueden quedar nulas. Por favor ingrese rango de fechas.", 
                    "HISTORIAL DE BUSQUEDA", 
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        LocalDate inicioPeriodo = inicio.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate finalPeriodo = fin.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        if (inicioPeriodo.isAfter(finalPeriodo)) {
            JOptionPane.showMessageDialog(this, 
                    "La fecha de inicio no puede ser posterior a la fecha final.", 
                    "ERROR DE FECHAS",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            List<DatosReporteEntradaDTO> listaResultados = control.listarHistorialEntradas(inicioPeriodo, finalPeriodo);
            
            if (listaResultados == null || listaResultados.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                        "No se encontraron resultados,", 
                        "SIN RESULTADOS", 
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
            
            for (DatosReporteEntradaDTO datos: listaResultados) {
                Object[] fila = new Object[5];
                fila[0] = datos.getIdProducto();
                fila[1] = datos.getNombre();
                fila[2] = datos.getPrecio();
                fila[3] = datos.getCantidad();
                fila[4] = (datos.getFechaHoraOperacion() != null) ? datos.getFechaHoraOperacion().format(dtf) : "";
                entradaProductos.addRow(fila);
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();
        btnRegresar = new BotonRedondeado();
        btnExportar = new BotonRedondeado();
        jDateInicio = new com.toedter.calendar.JDateChooser();
        jDateFinal = new com.toedter.calendar.JDateChooser();
        btnBuscar = new BotonRedondeado();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 150));
        jLabel1.setText("Historial de Entradas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 150));
        jLabel3.setText("Ingrese fecha de inicio:");

        jSeparator1.setForeground(new java.awt.Color(0, 255, 150));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 150));
        jLabel8.setText("Ingrese fecha de termino:");

        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID producto", "Nombre producto", "Precio", "Cantidad", "Fecha y Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbProductos);
        if (tbProductos.getColumnModel().getColumnCount() > 0) {
            tbProductos.getColumnModel().getColumn(4).setResizable(false);
        }

        btnRegresar.setBackground(new java.awt.Color(35, 35, 35));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 255, 150));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setFocusPainted(false);
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnExportar.setBackground(new java.awt.Color(35, 35, 35));
        btnExportar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExportar.setForeground(new java.awt.Color(0, 255, 150));
        btnExportar.setText("Exportar a PDF");
        btnExportar.setBorderPainted(false);
        btnExportar.setContentAreaFilled(false);
        btnExportar.setFocusPainted(false);
        btnExportar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExportarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExportarMouseExited(evt);
            }
        });
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(35, 35, 35));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 255, 150));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setFocusPainted(false);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(jDateFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(jDateInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(26, 26, 26)
                        .addComponent(jDateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        colorR.mouseEntered(evt);
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        colorR.mouseExited(evt);
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        control.mostrarGestionProductosFORM();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnExportarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarMouseEntered
        colorE.mouseEntered(evt);
    }//GEN-LAST:event_btnExportarMouseEntered

    private void btnExportarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarMouseExited
        colorE.mouseExited(evt);
    }//GEN-LAST:event_btnExportarMouseExited

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        Date inicio = jDateInicio.getDate();
        Date fin = jDateFinal.getDate();
        if (inicio == null || fin == null) {
            JOptionPane.showMessageDialog(this, 
                    "Las fechas no pueden quedar nulas. Por favor ingrese rango de fechas.", 
                    "HISTORIAL DE BUSQUEDA", 
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        LocalDate inicioPeriodo = inicio.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate finalPeriodo = fin.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        if (inicioPeriodo.isAfter(finalPeriodo)) {
            JOptionPane.showMessageDialog(this, 
                    "La fecha de inicio no puede ser posterior a la fecha final.", 
                    "ERROR DE FECHAS",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            List<DatosReporteEntradaDTO> listaResultados = control.listarHistorialEntradas(inicioPeriodo, finalPeriodo);
            
            if (listaResultados == null || listaResultados.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                        "No se encontraron resultados,", 
                        "SIN RESULTADOS", 
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            for (DatosReporteEntradaDTO datos: listaResultados) {
                Object[] fila = new Object[5];
                fila[0] = datos.getIdProducto();
                fila[1] = datos.getNombre();
                fila[2] = datos.getPrecio();
                fila[3] = datos.getCantidad();
                fila[4] = datos.getFechaFormato();
                entradaProductos.addRow(fila);
            }
            
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(listaResultados);
            InputStream reporte = getClass().getClassLoader().getResourceAsStream("reportes/HistorialDeEntradas.jasper");
            
            Map<String, Object> parametros = new HashMap<>();            
            parametros.put("fechaHoraOperacion", inicioPeriodo);
            parametros.put("fechaHoraOperacion", finalPeriodo);
            
            JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, parametros, dataSource);
            
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("GUARDAR REPORTE");
            
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos PDF (*.pdf)", "pdf");
            fileChooser.addChoosableFileFilter(filtro);
            fileChooser.setFileFilter(filtro);
            
            int result = fileChooser.showSaveDialog(null);
            if (result != JFileChooser.APPROVE_OPTION) {
                return;
            }
            File archivoGuardar = fileChooser.getSelectedFile();
            String archivoRuta = archivoGuardar.getAbsolutePath();
            if (!archivoRuta.toLowerCase().endsWith(".pdf")) {
                archivoRuta += ".pdf";
            }
            JasperExportManager.exportReportToPdfFile(jasperPrint, archivoRuta);
            JOptionPane.showMessageDialog(this, "Reporte Guardado correctamente");
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage());
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(this, "Error al generar reporte: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        colorB.mouseEntered(evt);
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        colorB.mouseExited(evt);
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        llenarTabla();
    }//GEN-LAST:event_btnBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnRegresar;
    private com.toedter.calendar.JDateChooser jDateFinal;
    private com.toedter.calendar.JDateChooser jDateInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbProductos;
    // End of variables declaration//GEN-END:variables
}

//--------------------