
package CUIInventario;

import Control.Control;
import ExploradorDeArchivos.SelectorDeImagen;
import GoOrderDTO.ProductoDTO;
import ModelosTabla.InventarioProductosTabla;
import Pattern.BotonRedondeado;
import Pattern.ColorBoton;
import java.awt.HeadlessException;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import org.example.NegocioException;

/**
 *
 * @author 
 */
public class InventarioProductosEntradaFORM extends javax.swing.JFrame {

    private final ColorBoton colorB;
    private final ColorBoton colorG;
    private final ColorBoton colorA;
    private final ColorBoton colorI;
    private final ColorBoton colorR;
    private final ColorBoton colorRtn;
    
    private final Control control;
    
    private final SpinnerNumberModel modeloSP;
    private InventarioProductosTabla inventarioTabla;
    
    private byte[] bytesImagenSeleccionada = null;
    
    private List<ProductoDTO> listaTemporal;
    
    public InventarioProductosEntradaFORM(Control control) throws NegocioException {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        listaTemporal = new ArrayList<>();
        this.control = control;

        List<ProductoDTO> productosTabla = control.listarProducto();
        this.inventarioTabla = new InventarioProductosTabla(productosTabla);
        this.tbProductos.setModel(this.inventarioTabla); 
        
        this.tbProductos.createDefaultColumnsFromModel();
        this.tbProductos.setRowHeight(55);
        
        colorB = new ColorBoton(btnBuscar);
        colorA = new ColorBoton(btnActualizar);
        colorI = new ColorBoton(btnImagen);
        colorR = new ColorBoton(btnRegistrar);
        colorRtn = new ColorBoton(btnRegresar);
        colorG = new ColorBoton(btnGuardar);
        
        modeloSP = new SpinnerNumberModel(1, 1, 100, 1);
        spCantidad.setModel(modeloSP);
        ((JSpinner.DefaultEditor) spCantidad.getEditor()).getTextField().setEditable(false);
    }
    
    private void llenarTabla() {
        String nombre = txtProducto.getText().trim();
        try {
            if (nombre == null || nombre.trim().isEmpty()) {
                List<ProductoDTO> listaProductos = control.obtenerListaProductos();
                this.inventarioTabla.actualizarDatos(listaProductos);
                return;
            }
            List<ProductoDTO> resultados = control.obtenerProducto(nombre);
            if (resultados == null || resultados.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron resultados con los datos ingresados.");
            } else {
                this.inventarioTabla.actualizarDatos(resultados);                
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage());
        }
    }
    
    private void limpiarCampos() {
        txtProducto.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtPrecio.setText("");
        
        lbImagen.setIcon(null);
        this.bytesImagenSeleccionada = null;
        spCantidad.setValue(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        spCantidad = new javax.swing.JSpinner();
        lbImagen = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnRegresar = new BotonRedondeado();
        btnImagen = new BotonRedondeado();
        btnRegistrar = new BotonRedondeado();
        btnActualizar = new BotonRedondeado();
        btnGuardar = new BotonRedondeado();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();
        btnBuscar = new BotonRedondeado();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 150));
        jLabel1.setText("Entrada de productos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 150));
        jLabel2.setText("Nombre del producto:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 150));
        jLabel3.setText("Ingresar nombre del producto:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 150));
        jLabel4.setText("Descripción del producto:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 150));
        jLabel5.setText("Imagen de producto:");

        jSeparator1.setForeground(new java.awt.Color(0, 255, 150));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 150));
        jLabel6.setText("Precio de producto:");

        lbImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 150)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 150));
        jLabel8.setText("Cantidad de producto:");

        btnRegresar.setBackground(new java.awt.Color(35, 35, 35));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 255, 150));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setFocusPainted(false);
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnImagen.setBackground(new java.awt.Color(35, 35, 35));
        btnImagen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnImagen.setForeground(new java.awt.Color(0, 255, 150));
        btnImagen.setText("Ingresar imagen");
        btnImagen.setBorderPainted(false);
        btnImagen.setContentAreaFilled(false);
        btnImagen.setFocusPainted(false);
        btnImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnImagenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnImagenMouseExited(evt);
            }
        });
        btnImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(35, 35, 35));
        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 255, 150));
        btnRegistrar.setText("Añadir a lista");
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseExited(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(35, 35, 35));
        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 255, 150));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorderPainted(false);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setFocusPainted(false);
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarMouseExited(evt);
            }
        });
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(35, 35, 35));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 255, 150));
        btnGuardar.setText("Guardar productos");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tbProductos);

        btnBuscar.setBackground(new java.awt.Color(35, 35, 35));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 255, 150));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setFocusPainted(false);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnRegistrar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lbImagen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(spCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                        .addComponent(btnImagen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(6, 6, 6))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGuardar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        control.mostrarGestionProductosFORM();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        colorRtn.mouseEntered(evt);
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        colorRtn.mouseExited(evt);
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnImagenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImagenMouseEntered
        colorI.mouseEntered(evt);
    }//GEN-LAST:event_btnImagenMouseEntered

    private void btnImagenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImagenMouseExited
        colorI.mouseExited(evt);
    }//GEN-LAST:event_btnImagenMouseExited

    private void btnImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenActionPerformed
        SelectorDeImagen selector = new SelectorDeImagen();
        
        selector.seleccionarImagen();
        
        byte[] imagenSeleccionadao = selector.obtenerBytesImagen();
        
        if (imagenSeleccionadao != null) {
            this.bytesImagenSeleccionada = imagenSeleccionadao;
            
            ImageIcon icono = new ImageIcon(imagenSeleccionadao);
            Image imagenEscala = icono.getImage().getScaledInstance(lbImagen.getWidth(), lbImagen.getHeight(), Image.SCALE_SMOOTH);
            lbImagen.setIcon(new ImageIcon(imagenEscala));
            lbImagen.revalidate();
            lbImagen.repaint();
        }
    }//GEN-LAST:event_btnImagenActionPerformed

    private void btnRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseEntered
        colorR.mouseEntered(evt);        
    }//GEN-LAST:event_btnRegistrarMouseEntered

    private void btnRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseExited
        colorR.mouseExited(evt);
    }//GEN-LAST:event_btnRegistrarMouseExited

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String nombre = txtNombre.getText();
        String descripcion = txtDescripcion.getText();
        String precio = txtPrecio.getText();
        Integer cantidad = (Integer) spCantidad.getValue();
        byte[] imagen = bytesImagenSeleccionada;
         
        boolean nombreProducto = nombre.trim().isEmpty();
        boolean descripcionProducto = descripcion.trim().isEmpty();
        boolean precioProducto = precio.trim().isEmpty();
        
        try {
            if (nombreProducto || descripcionProducto || precioProducto) {
                JOptionPane.showMessageDialog(this, "Los datos de nombre, descripción y precio no pueden quedar vacios para registrar un producto.");
                return;  
            }
            
            ProductoDTO productoTemporal = new ProductoDTO();
            int filaSelecciona = tbProductos.getSelectedRow();
            if (filaSelecciona != -1) {
                String id = this.inventarioTabla.obtenerProductoAt(filaSelecciona).getId();
                productoTemporal.setId(id);
            }
            
            productoTemporal.setNombre(nombre);
            productoTemporal.setDescripcion(descripcion);
            productoTemporal.setPrecio(Double.parseDouble(precio));            
            productoTemporal.setCantidadT(cantidad);
            productoTemporal.setImagenP(imagen);
            
            listaTemporal.add(productoTemporal);
            this.inventarioTabla.agregarFila(productoTemporal);
            JOptionPane.showMessageDialog(this, "Producto añadido a la lista correctamente.");
            limpiarCampos();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: No se pueden añadir caracteres especiales al precio del producto.");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int filaSeleccionada = tbProductos.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila para añadir stock de productos.");
            return;
        }
        
        int filaModelo = tbProductos.convertRowIndexToModel(filaSeleccionada);        
        ProductoDTO productoSeleccionado = this.inventarioTabla.obtenerProductoAt(filaModelo);
        
        Integer nuevaCantidadProducto = (Integer) spCantidad.getValue();
        
        ProductoDTO nuevoValor = new ProductoDTO();
        nuevoValor.setId(productoSeleccionado.getId());
        nuevoValor.setCantidadT(nuevaCantidadProducto);
        
        try {
            control.actualizarSumarProductoInventario(nuevoValor);
            //control.actualizarProducto(productoSeleccionado);
            this.inventarioTabla.fireTableRowsUpdated(filaModelo, filaModelo);
            
            JOptionPane.showMessageDialog(this, "Producto con nuevo stock actualizado correctamente.");
            llenarTabla();
            limpiarCampos();
            tbProductos.clearSelection();
        } catch (NegocioException ex) {
            Logger.getLogger(InventarioProductosEntradaFORM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (listaTemporal.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No existen productos en fila para registrar. Agrege al menos 1 producto para comenzar registro de producto(s)");
                return;
            }
            
            StringBuilder productosPorAniadir = new StringBuilder("¿Seguro desea añadir los siguientes productos?\n\n");
            for (ProductoDTO p: listaTemporal) {
                productosPorAniadir.append("-").append(p.getNombre()).append("\n");
            }            
            int confirmacion = JOptionPane.showConfirmDialog(
                    this,
                    productosPorAniadir.toString(),
                    "CONFIRMACIÓN",
                    JOptionPane.YES_NO_OPTION);
            if (confirmacion == JOptionPane.YES_OPTION) {
                control.nuevaEntradaProducto(listaTemporal);
                JOptionPane.showMessageDialog(
                        this, 
                        "Producto(s) añadidos correctamente", 
                        "REGISTRO EXITOSO",
                        JOptionPane.INFORMATION_MESSAGE);
                listaTemporal.clear();
                llenarTabla();
                limpiarCampos();        
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }               
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        colorG.mouseEntered(evt);
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        colorG.mouseExited(evt);
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseExited
        colorA.mouseExited(evt);
    }//GEN-LAST:event_btnActualizarMouseExited

    private void btnActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseEntered
        colorA.mouseEntered(evt);
    }//GEN-LAST:event_btnActualizarMouseEntered

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        colorB.mouseEntered(evt);
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        colorB.mouseExited(evt);
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nombreProducto = txtProducto.getText();        
        
        boolean nombre = nombreProducto.trim().isEmpty();

        try {
            if (nombre) {
                JOptionPane.showMessageDialog(this, "Ingrese un nombre para iniciar busqueda de producto.");
                List<ProductoDTO> resultadosNoCoiciden = control.obtenerListaProductos();
                this.inventarioTabla.actualizarDatos(resultadosNoCoiciden);
                return;
            }          
            List<ProductoDTO> productosEncontrado = control.obtenerProducto(nombreProducto);
            
            if (productosEncontrado.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No existen productos con los caracteres o nombre ingresado.");                
                return;
            }
            this.inventarioTabla.actualizarDatos(productosEncontrado);
            txtProducto.setText("");
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImagen;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbImagen;
    private javax.swing.JSpinner spCantidad;
    private javax.swing.JTable tbProductos;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}

//----------