
package GUI;

import Control.Control;
import Pattern.BotonRedondeado;
import Pattern.ColorBoton;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class GestionProductosFORM extends javax.swing.JFrame {
    
    private final ColorBoton colorES;
    private final ColorBoton colorH;
    private final ColorBoton colorC;
    private final Control control;
    
    public GestionProductosFORM(Control control) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        this.control = control;
        colorES = new ColorBoton(btnRegistroES);
        colorH = new ColorBoton(btnHistorial);
        colorC = new ColorBoton(btnConsultarProductos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHistorial = new BotonRedondeado();
        jLabel1 = new javax.swing.JLabel();
        btnRegistroES = new BotonRedondeado();
        btnConsultarProductos = new BotonRedondeado();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnHistorial.setBackground(new java.awt.Color(0, 0, 0));
        btnHistorial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHistorial.setForeground(new java.awt.Color(0, 255, 150));
        btnHistorial.setText("Historial productos");
        btnHistorial.setBorderPainted(false);
        btnHistorial.setContentAreaFilled(false);
        btnHistorial.setFocusPainted(false);
        btnHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHistorialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHistorialMouseExited(evt);
            }
        });
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 150));
        jLabel1.setText("Gestión Productos");

        btnRegistroES.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistroES.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistroES.setForeground(new java.awt.Color(0, 255, 150));
        btnRegistroES.setText("Registrar E/S productos");
        btnRegistroES.setBorderPainted(false);
        btnRegistroES.setContentAreaFilled(false);
        btnRegistroES.setFocusPainted(false);
        btnRegistroES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistroESMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroESMouseExited(evt);
            }
        });
        btnRegistroES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroESActionPerformed(evt);
            }
        });

        btnConsultarProductos.setBackground(new java.awt.Color(0, 0, 0));
        btnConsultarProductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConsultarProductos.setForeground(new java.awt.Color(0, 255, 150));
        btnConsultarProductos.setText("Consultar productos");
        btnConsultarProductos.setBorderPainted(false);
        btnConsultarProductos.setContentAreaFilled(false);
        btnConsultarProductos.setFocusPainted(false);
        btnConsultarProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultarProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultarProductosMouseExited(evt);
            }
        });
        btnConsultarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistroES, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(btnHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnRegistroES, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed

    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnHistorialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialMouseEntered
        colorH.mouseEntered(evt);
    }//GEN-LAST:event_btnHistorialMouseEntered

    private void btnHistorialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialMouseExited
        colorH.mouseExited(evt);
    }//GEN-LAST:event_btnHistorialMouseExited

    private void btnRegistroESMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroESMouseEntered
        colorES.mouseEntered(evt);        
    }//GEN-LAST:event_btnRegistroESMouseEntered

    private void btnRegistroESMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroESMouseExited
        colorES.mouseExited(evt);
    }//GEN-LAST:event_btnRegistroESMouseExited

    private void btnRegistroESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroESActionPerformed
        String[] opciones = {"Registro Entrada", "Registro Salida"};
        int seleccion = JOptionPane.showOptionDialog
        (
            this,
            "Entrada y Salida de productos",
            "Inventario",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]
        );
        
        if (seleccion == 0) {
            control.mostrarInventarioFORM();
        }
        
    }//GEN-LAST:event_btnRegistroESActionPerformed

    private void btnConsultarProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarProductosMouseEntered
        colorC.mouseEntered(evt);
    }//GEN-LAST:event_btnConsultarProductosMouseEntered

    private void btnConsultarProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarProductosMouseExited
        colorC.mouseExited(evt);
    }//GEN-LAST:event_btnConsultarProductosMouseExited

    private void btnConsultarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarProductosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarProductos;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnRegistroES;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}